# Enum types  and other constants will be defined here.

QUESTION = "QUESTION"
INCIDENT = "INCIDENT"
PROBLEM = "PROBLEM"
FEATURE_REQUEST = "FEATURE_REQUEST"
REFUND = "REFUND"
TASK_TYPE_MAPPING = {
    "QUESTION": QUESTION,
    "INCIDENT": INCIDENT,
    "PROBLEM": PROBLEM,
    "FEATURE_REQUEST": FEATURE_REQUEST,
    "REFUND": REFUND
}

ADMIN = "ADMIN"
REGULAR = "REGULAR"
ROLE_MAPPING = {
    "ADMIN": ADMIN,  # full access.
    "REGULAR": REGULAR  # only read write access.
}

STUDENT = "STUDENT"
EMPLOYEE = "EMPLOYEE"
USER_TYPE_MAPPING = {
    "STUDENT": STUDENT,
    "EMPLOYEE": EMPLOYEE
}

LOW = "LOW"
MEDIUM = "MEDIUM"
HIGH = "HIGH"
URGENT = "URGENT"
TASK_PRIORITY_MAPPING = {
    "LOW": LOW,
    "MEDIUM": MEDIUM,
    "HIGH": HIGH,
    "URGENT": URGENT
}

SCREEN = "SCREEN"
ASSIGNED = "ASSIGNED"
RESOLVED = "RESOLVED"
BLOCKED = "BLOCKED"
UNBLOCKED = "UNBLOCKED"
TASK_STATE_MAPPING = {
    "SCREEN": SCREEN,
    "ASSIGNED": ASSIGNED,
    "RESOLVED": RESOLVED,
    "BLOCKED": BLOCKED,
    "UNBLOCKED": UNBLOCKED
}
