"""empty message

Revision ID: d53399f26d66
Revises: 
Create Date: 2021-06-17 23:59:58.210858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53399f26d66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('department_name', sa.String(length=80), nullable=False),
    sa.Column('department_email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_email'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REGULAR', name='role'), nullable=True),
    sa.Column('user_type', sa.Enum('STUDENT', 'EMPLOYEE', name='usertype'), nullable=True),
    sa.Column('itu_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_department_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept_id', 'emp_id')
    )
    op.create_table('screener_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept_id'),
    sa.UniqueConstraint('emp_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('QUESTION', 'INCIDENT', 'PROBLEM', 'FEATURE_REQUEST', 'REFUND', name='tasktype'), nullable=True),
    sa.Column('task_state', sa.Enum('SCREEN', 'ASSIGNED', 'RESOLVED', 'BLOCKED', 'UNBLOCKED', name='taskstate'), nullable=True),
    sa.Column('task_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('originator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['originator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('attachment_name', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('originator_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['originator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('discussion_text', sa.Text(), nullable=True),
    sa.Column('originator_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['originator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussion')
    op.drop_table('attachment')
    op.drop_table('task')
    op.drop_table('screener_info')
    op.drop_table('employee_department_mapping')
    op.drop_table('user')
    op.drop_table('department')
    # ### end Alembic commands ###
